### ISSUE TITLE
User-friendly stats board

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/jenkins_statistics#1]
I was wondering whether we could make the generation of the stats board more user-friendly. I'm thinking of a few rake tasks:
- `rake init:config`: Essentially `cp .env.example .env`.
- `rake init:dashing`: Executes the instructions on [the Dashing website](http://shopify.github.io/dashing/).
- `rake init`: Runs the above tasks.
- `rake projects:add <project-name>`: Adds the project to the config and does what is necessary to get it on the dashboard.
  ...

@ionut998, you've probably got a better idea than me which tasks need doing.

**Comment by lpil** [comment]
To me those init tasks seem more confusing than regular instructions in the README.

**Comment by jonnyarnold** [comment]
To me, instructions like 

```
rake init
rake projects:add reevoo/revieworld
```

is going to be a lot easier than following any manual instructions.

**Comment by lpil** [comment]
The instructions are only a few lines, and you actually know what it's doing. I don't think it's complicated enough to warrant an opaque command, and people should know what changes you're making to their machine.

The adding a project one could be good though

**Comment by ionut998** [comment]
I will add the setup script if the setup becomes more complex. For now the setup is quite easy
